CREATE TABLE apps
(
    id INT(11) PRIMARY KEY NOT NULL,
    name VARCHAR(64) NOT NULL,
    author VARCHAR(128) NOT NULL,
    appId VARCHAR(64) NOT NULL,
    secureId VARCHAR(128) NOT NULL,
    pkg VARCHAR(128) NOT NULL,
    error_pkg VARCHAR(128) NOT NULL,
    push VARCHAR(128) NOT NULL,
    notify INT(11) NOT NULL,
    disabled INT(11) NOT NULL
);
CREATE TABLE reports
(
    app VARCHAR(64) NOT NULL,
    PACKAGE_NAME VARCHAR(255) NOT NULL,
    APP_VERSION_NAME VARCHAR(255) NOT NULL,
    APP_VERSION_CODE INT(11) NOT NULL,
    ANDROID_VERSION VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_COMMENT VARCHAR(1024) NOT NULL,
    DEVICE_FEATURES VARCHAR(2000) NOT NULL,
    PHONE_MODEL VARCHAR(255) NOT NULL,
    SETTINGS_SECURE TEXT NOT NULL,
    INSTALLATION_ID VARCHAR(255) NOT NULL,
    SETTINGS_SYSTEM TEXT NOT NULL,
    SHARED_PREFERENCES TEXT NOT NULL,
    IS_SILENT INT(11) NOT NULL,
    CRASH_CONFIGURATION TEXT NOT NULL,
    USER_CRASH_DATE VARCHAR(255) NOT NULL,
    DUMPSYS_MEMINFO TEXT NOT NULL,
    BUILD TEXT NOT NULL,
    STACK_TRACE TEXT NOT NULL,
    PRODUCT VARCHAR(255) NOT NULL,
    DISPLAY VARCHAR(1024) NOT NULL,
    LOGCAT TEXT NOT NULL,
    AVAILABLE_MEM_SIZE INT(11) NOT NULL,
    USER_APP_START_DATE VARCHAR(255) NOT NULL,
    CUSTOM_DATA TEXT NOT NULL,
    BRAND VARCHAR(255) NOT NULL,
    INITIAL_CONFIGURATION TEXT NOT NULL,
    TOTAL_MEM_SIZE INT(11) NOT NULL,
    FILE_PATH VARCHAR(255) NOT NULL,
    ENVIRONMENT TEXT NOT NULL,
    REPORT_ID VARCHAR(255) NOT NULL,
    DEVICE_ID VARCHAR(255) DEFAULT '',
    DROPBOX TEXT DEFAULT '',
    EVENTSLOG TEXT DEFAULT '',
    RADIOLOG TEXT DEFAULT '',
    SETTINGS_GLOBAL TEXT DEFAULT '',
    RESOLVED INT(11) DEFAULT '0' NOT NULL
);
CREATE TABLE users
(
    id INT(11) NOT NULL,
    email VARCHAR(64) NOT NULL,
    hash VARCHAR(128) NOT NULL,
    token VARCHAR(256) NOT NULL,
    name VARCHAR(128) NOT NULL,
    verificaton_code VARCHAR(256) NOT NULL,
    verificated INT(11) NOT NULL
);
CREATE INDEX id ON users (id);
CREATE UNIQUE INDEX id_2 ON users (id);
CREATE TABLE backup
(
    id INT(11) PRIMARY KEY NOT NULL,
    app VARCHAR(16),
    date INT(11)
);
